### ISSUE TITLE
You seem to have an invalid version (3.0.1.1) of wxWidgets installed. This program needs version 2.8.

### ISSUE THREAD

**Issue by jipipayo** [oskusalerma/trelby#363] opened 2015-05-07 19:03 UTC
doesn't works under debian testing
cat /etc/debian_version 
8.0
python --version
Python 2.7.9

maybe you could allow an "unstable" running, with a warning window, but allowing to use the software?

**Comment by jipipayo** [comment] 2015-05-07 19:18
hummm no, i removed the warning and it crashes completly:

dani@zinpa:/opt/trelby/src$ ./trelby.py 
Traceback (most recent call last):
  File "./trelby.py", line 2691, in <module>
    main()
  File "./trelby.py", line 2688, in main
    myApp = MyApp(0)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8628, in __init__
    self._BootstrapApp()
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "./trelby.py", line 2640, in OnInit
    refreshGuiConfig()
  File "./trelby.py", line 66, in refreshGuiConfig
    cfgGui = config.ConfigGui(cfgGl)
  File "/opt/trelby/src/config.py", line 1349, in __init__
    nfi.SetEncoding(wx.FONTENCODING_ISO8859_1)
  File "/usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/_gdi.py", line 1947, in SetEncoding
    return _gdi_.NativeFontInfo_SetEncoding(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "Assert failure" failed at ../src/unix/fontutil.cpp(374) in SetEncoding(): not implemented: Pango encoding is always UTF8
../src/gtk/dcclient.cpp(250): assert "Assert failure" failed in wxFreePoolGC(): Wrong GC
../src/gtk/dcclient.cpp(250): assert "Assert failure" failed in wxFreePoolGC(): Wrong GC
../src/gtk/dcclient.cpp(250): assert "Assert failure" failed in wxFreePoolGC(): Wrong GC
../src/gtk/dcclient.cpp(250): assert "Assert failure" failed in wxFreePoolGC(): Wrong GC

**Comment by onlyjob** [comment] 2015-06-29 10:16
This bug is a duplicate of #354.

**Comment by oskusalerma** [comment] 2015-08-02 13:20
Duplicate, closing.

**Closed by oskusalerma** 2015-08-02 13:20 UTC
